import express from "express";
import crypto from "crypto";
import pool from "../config/db.js";
import { authenticateUser } from "../middleware/authMiddleware.js";
import { requirePermission } from "../middleware/permissionMiddleware.js";

const router = express.Router(); router.use(authenticateUser);
const clean = (v) => v === "" || v === undefined ? null : v;
async function institutionId(req) { if (req.user.institution_id) return req.user.institution_id; const r=await pool.query("SELECT institution_id FROM sms.institutions WHERE status='ACTIVE' LIMIT 1"); return r.rows[0]?.institution_id; }
async function branchId(req, requested) { const inst=await institutionId(req); const r=await pool.query("SELECT branch_id FROM sms.branches WHERE institution_id=$1 AND status='ACTIVE' AND (branch_id=$2 OR $2 IS NULL) ORDER BY is_main_branch DESC,branch_id LIMIT 1",[inst,clean(requested)||clean(req.user.branch_id)]); return r.rows[0]?.branch_id; }
const fail=(res,error,message)=>{ console.error(message,error); res.status(500).json({success:false,message}); };
const curriculumTypes = ['ALL','SCHOOL','COLLEGE','MADRASA','COACHING_CENTER','UNIVERSITY','POLYTECHNIC','VOCATIONAL_INSTITUTE'];
const allowedCurriculums = (institutionType) => {
  const type = String(institutionType || '').trim().toUpperCase();
  // Legacy or unfinished institution profiles without a type can use every subject curriculum.
  if (!type) return curriculumTypes;
  if (type.includes('SCHOOL') && type.includes('COLLEGE')) return ['ALL','SCHOOL','COLLEGE'];
  if (type.includes('MADRASA')) return ['ALL','MADRASA'];
  if (type.includes('COACHING')) return ['ALL','COACHING_CENTER'];
  if (type.includes('UNIVERSITY')) return ['ALL','UNIVERSITY'];
  if (type.includes('POLYTECHNIC')) return ['ALL','POLYTECHNIC'];
  if (type.includes('VOCATIONAL')) return ['ALL','VOCATIONAL_INSTITUTE'];
  if (type.includes('COLLEGE')) return ['ALL','COLLEGE'];
  return ['ALL','SCHOOL'];
};
async function institutionCurriculums(inst) {
  const row = (await pool.query('SELECT institution_type FROM sms.institutions WHERE institution_id=$1',[inst])).rows[0];
  return { institutionType: row?.institution_type || '', allowed: allowedCurriculums(row?.institution_type) };
}
const curriculumInput = (value) => {
  const type = String(value || '').trim().toUpperCase();
  return type === 'MADRASAH' ? 'MADRASA' : type;
};
const subjectFail = (res, error, fallback) => {
  if (error?.code === 'ER_DUP_ENTRY') {
    return res.status(409).json({ success: false, message: 'This subject code already exists for the institution. Use a different code.' });
  }
  return fail(res, error, fallback);
};

router.get("/lookups", requirePermission("exam.management","view"), async(req,res)=>{ try { const inst=await institutionId(req), curriculum=await institutionCurriculums(inst); const placeholders=curriculum.allowed.map((_,index)=>`$${index+2}`).join(','); const [types,scales,branches,years,classes,subjects,students]=await Promise.all([
  pool.query("SELECT * FROM sms.exam_types WHERE institution_id=$1 AND status='ACTIVE' ORDER BY exam_type_name",[inst]), pool.query("SELECT * FROM sms.grading_scales WHERE institution_id=$1 AND status='ACTIVE' ORDER BY scale_name",[inst]),
  pool.query("SELECT branch_id,branch_name FROM sms.branches WHERE institution_id=$1 AND status='ACTIVE' ORDER BY is_main_branch DESC,branch_name",[inst]), pool.query("SELECT academic_year_id,year_name FROM sms.academic_years WHERE institution_id=$1 AND status='ACTIVE' ORDER BY is_current DESC,academic_year_id DESC",[inst]),
  pool.query("SELECT class_id,class_name FROM sms.class_levels WHERE institution_id=$1 AND status='ACTIVE' ORDER BY numeric_level,class_id",[inst]), pool.query(`SELECT subject_id,subject_code,subject_name,curriculum_type FROM sms.subjects WHERE institution_id=$1 AND status='ACTIVE' AND curriculum_type IN (${placeholders}) ORDER BY subject_name`,[inst,...curriculum.allowed]),
  pool.query("SELECT s.student_id,s.student_no,s.full_name,se.enrollment_id,se.branch_id,se.academic_year_id,se.class_id FROM sms.students s JOIN sms.student_enrollments se ON se.student_id=s.student_id AND se.enrollment_status='ACTIVE' WHERE s.institution_id=$1 AND s.status='ACTIVE' ORDER BY s.full_name",[inst])]); res.json({success:true,data:{types:types.rows,scales:scales.rows,branches:branches.rows,years:years.rows,classes:classes.rows,subjects:subjects.rows,students:students.rows,institution_type:curriculum.institutionType,allowed_curriculum_types:curriculum.allowed}}); }catch(e){fail(res,e,"Failed to load exam setup data.");} });
router.get("/dashboard",requirePermission("exam.management","view"),async(req,res)=>{try{const inst=await institutionId(req);const [exams,marks,results]=await Promise.all([pool.query("SELECT e.*,et.exam_type_name,cl.class_name FROM sms.exams e JOIN sms.branches b ON b.branch_id=e.branch_id LEFT JOIN sms.exam_types et ON et.exam_type_id=e.exam_type_id LEFT JOIN sms.class_levels cl ON cl.class_id=e.class_id WHERE b.institution_id=$1 ORDER BY e.exam_id DESC LIMIT 8",[inst]),pool.query("SELECT COUNT(*) total,SUM(entry_status='VERIFIED') verified FROM sms.exam_marks em JOIN sms.exam_subjects es ON es.exam_subject_id=em.exam_subject_id JOIN sms.exams e ON e.exam_id=es.exam_id JOIN sms.branches b ON b.branch_id=e.branch_id WHERE b.institution_id=$1",[inst]),pool.query("SELECT COUNT(*) total,SUM(result_status='PASSED') passed FROM sms.student_results sr JOIN sms.exams e ON e.exam_id=sr.exam_id JOIN sms.branches b ON b.branch_id=e.branch_id WHERE b.institution_id=$1",[inst])]);res.json({success:true,data:{exams:exams.rows,marks:marks.rows[0],results:results.rows[0]}})}catch(e){fail(res,e,"Failed to load exam dashboard.")}});
router.get("/dashboard/overview",requirePermission("exam.management","view"),async(req,res)=>{try{const inst=await institutionId(req);const [examStats,candidateStats,attendanceStats,resultStats,recentExams]=await Promise.all([
  pool.query("SELECT COUNT(*) total_exams,SUM(e.exam_status='SCHEDULED') scheduled_exams,SUM(e.exam_status='DRAFT') draft_exams,SUM(e.exam_status='COMPLETED') completed_exams FROM sms.exams e JOIN sms.branches b ON b.branch_id=e.branch_id WHERE b.institution_id=$1",[inst]),
  pool.query("SELECT COUNT(*) total_candidates FROM sms.exam_candidates ec JOIN sms.exams e ON e.exam_id=ec.exam_id JOIN sms.branches b ON b.branch_id=e.branch_id WHERE b.institution_id=$1",[inst]),
  pool.query("SELECT COUNT(*) recorded_entries,SUM(em.is_absent=0) attended_entries,SUM(em.is_absent=1) absent_entries,COUNT(DISTINCT CASE WHEN em.is_absent=0 THEN CONCAT(es.exam_id,'-',em.student_id) END) attended_students FROM sms.exam_marks em JOIN sms.exam_subjects es ON es.exam_subject_id=em.exam_subject_id JOIN sms.exams e ON e.exam_id=es.exam_id JOIN sms.branches b ON b.branch_id=e.branch_id WHERE b.institution_id=$1",[inst]),
  pool.query("SELECT COUNT(*) total_results,SUM(sr.result_status='PASSED') passed,SUM(sr.result_status='FAILED') failed,SUM(sr.result_status='PENDING') pending FROM sms.student_results sr JOIN sms.exams e ON e.exam_id=sr.exam_id JOIN sms.branches b ON b.branch_id=e.branch_id WHERE b.institution_id=$1",[inst]),
  pool.query("SELECT e.exam_id,e.exam_name,e.exam_status,e.start_date,e.end_date,et.exam_type_name,cl.class_name,COUNT(DISTINCT ec.candidate_id) candidate_count,SUM(CASE WHEN sr.result_status='PASSED' THEN 1 ELSE 0 END) passed_count,SUM(CASE WHEN sr.result_status='FAILED' THEN 1 ELSE 0 END) failed_count FROM sms.exams e JOIN sms.branches b ON b.branch_id=e.branch_id LEFT JOIN sms.exam_types et ON et.exam_type_id=e.exam_type_id LEFT JOIN sms.class_levels cl ON cl.class_id=e.class_id LEFT JOIN sms.exam_candidates ec ON ec.exam_id=e.exam_id LEFT JOIN sms.student_results sr ON sr.exam_id=e.exam_id WHERE b.institution_id=$1 GROUP BY e.exam_id,e.exam_name,e.exam_status,e.start_date,e.end_date,et.exam_type_name,cl.class_name ORDER BY e.exam_id DESC LIMIT 7",[inst])
]);const summary={...(examStats.rows[0]||{}),...(candidateStats.rows[0]||{}),...(attendanceStats.rows[0]||{}),...(resultStats.rows[0]||{})};res.json({success:true,data:{summary,recent_exams:recentExams.rows}})}catch(e){fail(res,e,"Failed to load exam dashboard overview.")}});
router.get("/types",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT * FROM sms.exam_types WHERE institution_id=$1 ORDER BY exam_type_name",[await institutionId(req)]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load exam types.")}});
router.get("/subjects",requirePermission("subject.management","view"),async(req,res)=>{try{const inst=await institutionId(req),filter=curriculumInput(req.query.curriculum_type);if(filter&&!curriculumTypes.includes(filter))return res.status(400).json({success:false,message:'Invalid curriculum type.'});if(req.user.is_super_admin){const sql=filter?"SELECT s.*,i.institution_name,i.institution_type FROM sms.subjects s LEFT JOIN sms.institutions i ON i.institution_id=s.institution_id WHERE s.curriculum_type=$1 ORDER BY i.institution_name,s.subject_name":"SELECT s.*,i.institution_name,i.institution_type FROM sms.subjects s LEFT JOIN sms.institutions i ON i.institution_id=s.institution_id ORDER BY i.institution_name,s.subject_name";const r=await pool.query(sql,filter?[filter]:[]);return res.json({success:true,data:r.rows,meta:{is_super_admin:true,allowed_curriculum_types:curriculumTypes}})}const curriculum=await institutionCurriculums(inst),allowed=filter&&curriculum.allowed.includes(filter)?[filter]:curriculum.allowed,placeholders=allowed.map((_,index)=>`$${index+2}`).join(',');const r=await pool.query(`SELECT * FROM sms.subjects WHERE institution_id=$1 AND curriculum_type IN (${placeholders}) ORDER BY subject_name`,[inst,...allowed]);res.json({success:true,data:r.rows,meta:{institution_type:curriculum.institutionType,allowed_curriculum_types:curriculum.allowed}})}catch(e){fail(res,e,"Failed to load subjects.")}});
router.put("/subjects/:id/curriculum",requirePermission("subject.management","update"),async(req,res)=>{try{const inst=await institutionId(req),type=curriculumInput(req.body.curriculum_type),curriculum=await institutionCurriculums(inst);if(!curriculumTypes.includes(type))return res.status(400).json({success:false,message:'Select a valid institution curriculum.'});if(!req.user.is_super_admin&&!curriculum.allowed.includes(type))return res.status(403).json({success:false,message:`This institution can use only: ${curriculum.allowed.join(', ')}.`});const sql=req.user.is_super_admin?'UPDATE sms.subjects SET curriculum_type=$1 WHERE subject_id=$2 RETURNING *':'UPDATE sms.subjects SET curriculum_type=$1 WHERE subject_id=$2 AND institution_id=$3 RETURNING *';const r=await pool.query(sql,req.user.is_super_admin?[type,req.params.id]:[type,req.params.id,inst]);if(!r.rowCount)return res.status(404).json({success:false,message:'Subject not found.'});res.json({success:true,data:r.rows[0]})}catch(e){fail(res,e,'Failed to update curriculum type.')}});
router.put("/subjects/:id/status",requirePermission("subject.management","update"),async(req,res)=>{try{const inst=await institutionId(req),status=String(req.body.status||'').toUpperCase();if(!['ACTIVE','INACTIVE'].includes(status))return res.status(400).json({success:false,message:'Status must be ACTIVE or INACTIVE.'});const sql=req.user.is_super_admin?'UPDATE sms.subjects SET status=$1 WHERE subject_id=$2 RETURNING *':'UPDATE sms.subjects SET status=$1 WHERE subject_id=$2 AND institution_id=$3 RETURNING *';const r=await pool.query(sql,req.user.is_super_admin?[status,req.params.id]:[status,req.params.id,inst]);if(!r.rowCount)return res.status(404).json({success:false,message:'Subject not found.'});res.json({success:true,data:r.rows[0]})}catch(e){fail(res,e,'Failed to update subject status.')}});
router.put("/subjects/:id/bangla-name",requirePermission("subject.management","update"),async(req,res)=>{try{const inst=await institutionId(req),name=String(req.body.subject_name_bn||'').trim(),sql=req.user.is_super_admin?'UPDATE sms.subjects SET subject_name_bn=$1 WHERE subject_id=$2 RETURNING *':'UPDATE sms.subjects SET subject_name_bn=$1 WHERE subject_id=$2 AND institution_id=$3 RETURNING *',r=await pool.query(sql,req.user.is_super_admin?[name||null,req.params.id]:[name||null,req.params.id,inst]);if(!r.rowCount)return res.status(404).json({success:false,message:'Subject not found.'});res.json({success:true,data:r.rows[0]})}catch(e){fail(res,e,'Failed to update Bangla subject name.')}});
router.post("/subjects",requirePermission("subject.management","create"),async(req,res)=>{try{const b=req.body,inst=await institutionId(req),curriculum=await institutionCurriculums(inst),code=String(b.subject_code||'').trim().toUpperCase(),name=String(b.subject_name||'').trim(),type=String(b.subject_type||'MAIN').toUpperCase(),subjectCurriculum=curriculumInput(b.curriculum_type)||curriculum.allowed[0],full=Number(b.full_marks||0),written=Number(b.written_marks||0),mcq=Number(b.mcq_marks||0),practical=Number(b.practical_marks||0),viva=Number(b.viva_marks||0);if(!code||!name||!['MAIN','OPTIONAL','FOURTH_SUBJECT'].includes(type)||full<=0)return res.status(400).json({success:false,message:'Code, name, valid type and full marks are required.'});if(!curriculumTypes.includes(subjectCurriculum)||(!req.user.is_super_admin&&!curriculum.allowed.includes(subjectCurriculum)))return res.status(403).json({success:false,message:`This institution can use only: ${curriculum.allowed.join(', ')}.`});if(Math.abs(full-(written+mcq+practical+viva))>0.01)return res.status(400).json({success:false,message:'Written, MCQ, Practical and Viva marks must equal full marks.'});const r=await pool.query("INSERT INTO sms.subjects (institution_id,subject_code,subject_name,curriculum_type,subject_type,full_marks,pass_marks,written_marks,mcq_marks,practical_marks,viva_marks,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'ACTIVE') RETURNING *",[inst,code,name,subjectCurriculum,type,full,Number(b.pass_marks||0),written,mcq,practical,viva]);res.status(201).json({success:true,data:r.rows[0]})}catch(e){subjectFail(res,e,'Failed to save subject.')}});
router.put("/subjects/:id",requirePermission("subject.management","update"),async(req,res)=>{try{const b=req.body,inst=await institutionId(req),curriculum=await institutionCurriculums(inst),code=String(b.subject_code||'').trim().toUpperCase(),name=String(b.subject_name||'').trim(),type=String(b.subject_type||'MAIN').toUpperCase(),subjectCurriculum=curriculumInput(b.curriculum_type),full=Number(b.full_marks||0),written=Number(b.written_marks||0),mcq=Number(b.mcq_marks||0),practical=Number(b.practical_marks||0),viva=Number(b.viva_marks||0);if(!code||!name||!['MAIN','OPTIONAL','FOURTH_SUBJECT'].includes(type)||full<=0||Math.abs(full-(written+mcq+practical+viva))>0.01)return res.status(400).json({success:false,message:'Provide valid subject details; component total must equal full marks.'});if(!curriculumTypes.includes(subjectCurriculum)||(!req.user.is_super_admin&&!curriculum.allowed.includes(subjectCurriculum)))return res.status(403).json({success:false,message:`This institution can use only: ${curriculum.allowed.join(', ')}.`});const sql=req.user.is_super_admin?"UPDATE sms.subjects SET subject_code=$1,subject_name=$2,curriculum_type=$3,subject_type=$4,full_marks=$5,pass_marks=$6,written_marks=$7,mcq_marks=$8,practical_marks=$9,viva_marks=$10 WHERE subject_id=$11 RETURNING *":"UPDATE sms.subjects SET subject_code=$1,subject_name=$2,curriculum_type=$3,subject_type=$4,full_marks=$5,pass_marks=$6,written_marks=$7,mcq_marks=$8,practical_marks=$9,viva_marks=$10 WHERE subject_id=$11 AND institution_id=$12 RETURNING *";const values=[code,name,subjectCurriculum,type,full,Number(b.pass_marks||0),written,mcq,practical,viva,req.params.id];if(!req.user.is_super_admin)values.push(inst);const r=await pool.query(sql,values);if(!r.rowCount)return res.status(404).json({success:false,message:'Subject not found.'});res.json({success:true,data:r.rows[0]})}catch(e){subjectFail(res,e,'Failed to update subject.')}});
router.delete("/subjects/:id",requirePermission("subject.management","delete"),async(req,res)=>{try{const inst=await institutionId(req),sql=req.user.is_super_admin?"DELETE FROM sms.subjects WHERE subject_id=$1 RETURNING subject_id":"DELETE FROM sms.subjects WHERE subject_id=$1 AND institution_id=$2 RETURNING subject_id",r=await pool.query(sql,req.user.is_super_admin?[req.params.id]:[req.params.id,inst]);if(!r.rowCount)return res.status(404).json({success:false,message:'Subject not found.'});res.json({success:true})}catch(e){fail(res,e,'Failed to delete subject.')}});
router.post("/exams/:id/subjects",requirePermission("exam.management","update"),async(req,res,next)=>{try{const r=await pool.query("SELECT s.subject_id FROM sms.subjects s JOIN sms.exams e ON e.exam_id=$1 JOIN sms.branches b ON b.branch_id=e.branch_id WHERE s.subject_id=$2 AND s.institution_id=b.institution_id AND s.status='ACTIVE'",[req.params.id,req.body.subject_id]);if(!r.rowCount)return res.status(400).json({success:false,message:'Only an active subject can be added to a new exam transaction.'});next()}catch(e){fail(res,e,'Failed to validate subject status.')}});
router.get("/classes/:classId/subjects",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT cs.*,s.subject_code,s.subject_name,s.curriculum_type,s.full_marks,s.pass_marks FROM sms.class_subjects cs JOIN sms.subjects s ON s.subject_id=cs.subject_id WHERE cs.class_id=$1 AND cs.institution_id=$2 AND cs.status='ACTIVE' ORDER BY cs.sort_order,s.subject_name",[req.params.classId,await institutionId(req)]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load class subjects.")}});
router.post("/classes/:classId/subjects",requirePermission("subject.management","update"),async(req,res)=>{try{const subjectId=req.body.subject_id;if(!subjectId)return res.status(400).json({success:false,message:"Subject is required."});const inst=await institutionId(req);const subject=(await pool.query("SELECT subject_id FROM sms.subjects WHERE subject_id=$1 AND institution_id=$2 AND status='ACTIVE'",[subjectId,inst])).rows[0];if(!subject)return res.status(400).json({success:false,message:"Invalid subject."});await pool.query("INSERT INTO sms.class_subjects (institution_id,class_id,subject_id,is_mandatory,sort_order,status) VALUES ($1,$2,$3,$4,$5,'ACTIVE') ON DUPLICATE KEY UPDATE is_mandatory=VALUES(is_mandatory),sort_order=VALUES(sort_order),status='ACTIVE'",[inst,req.params.classId,subjectId,req.body.is_mandatory===false?0:1,Number(req.body.sort_order||0)]);res.status(201).json({success:true})}catch(e){fail(res,e,"Failed to assign class subject.")}});
router.put("/class-subjects/:id",requirePermission("subject.management","update"),async(req,res)=>{try{const r=await pool.query("UPDATE sms.class_subjects SET is_mandatory=$1,sort_order=$2,status='ACTIVE' WHERE class_subject_id=$3 AND institution_id=$4 RETURNING *",[req.body.is_mandatory===false?0:1,Number(req.body.sort_order||0),req.params.id,await institutionId(req)]);if(!r.rowCount)return res.status(404).json({success:false,message:'Class subject not found.'});res.json({success:true,data:r.rows[0]})}catch(e){fail(res,e,'Failed to update class subject.')}});
router.delete("/class-subjects/:id",requirePermission("subject.management","delete"),async(req,res)=>{try{const r=await pool.query("DELETE FROM sms.class_subjects WHERE class_subject_id=$1 AND institution_id=$2",[req.params.id,await institutionId(req)]);if(!r.rowCount)return res.status(404).json({success:false,message:"Class subject not found."});res.json({success:true})}catch(e){fail(res,e,"Failed to remove class subject.")}});
router.post("/types",requirePermission("exam.management","create"),async(req,res)=>{try{const code=String(req.body.exam_type_code||"").trim().toUpperCase(),name=String(req.body.exam_type_name||"").trim();if(!code||!name)return res.status(400).json({success:false,message:"Exam type code and name are required."});const r=await pool.query("INSERT INTO sms.exam_types (institution_id,exam_type_code,exam_type_name,status) VALUES ($1,$2,$3,'ACTIVE') RETURNING *",[await institutionId(req),code,name]);res.status(201).json({success:true,data:r.rows[0]})}catch(e){fail(res,e,"Failed to save exam type.")}});
router.get("/exams",requirePermission("exam.management","view"),async(req,res)=>{try{const inst=await institutionId(req);const r=await pool.query("SELECT e.*,et.exam_type_name,ay.year_name,cl.class_name,gs.scale_name FROM sms.exams e JOIN sms.branches b ON b.branch_id=e.branch_id LEFT JOIN sms.exam_types et ON et.exam_type_id=e.exam_type_id LEFT JOIN sms.academic_years ay ON ay.academic_year_id=e.academic_year_id LEFT JOIN sms.class_levels cl ON cl.class_id=e.class_id LEFT JOIN sms.grading_scales gs ON gs.grading_scale_id=e.grading_scale_id WHERE b.institution_id=$1 ORDER BY e.exam_id DESC",[inst]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load exams.")}});
router.post("/exams",requirePermission("exam.management","create"),async(req,res)=>{try{const b=await branchId(req,req.body.branch_id);if(!b||!req.body.academic_year_id||!req.body.exam_type_id||!req.body.exam_name)return res.status(400).json({success:false,message:"Branch, academic year, type and exam name are required."});const r=await pool.query("INSERT INTO sms.exams (branch_id,academic_year_id,exam_type_id,grading_scale_id,exam_name,class_id,start_date,end_date,result_publish_date,exam_status,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'DRAFT',$10) RETURNING *",[b,req.body.academic_year_id,req.body.exam_type_id,clean(req.body.grading_scale_id),req.body.exam_name,clean(req.body.class_id),clean(req.body.start_date),clean(req.body.end_date),clean(req.body.result_publish_date),req.user.user_id]);res.status(201).json({success:true,data:r.rows[0]})}catch(e){fail(res,e,"Failed to create exam.")}});
router.put("/exams/:id",requirePermission("exam.management","update"),async(req,res)=>{try{const b=await branchId(req,req.body.branch_id);const r=await pool.query("UPDATE sms.exams SET branch_id=$1,academic_year_id=$2,exam_type_id=$3,grading_scale_id=$4,exam_name=$5,class_id=$6,start_date=$7,end_date=$8,result_publish_date=$9 WHERE exam_id=$10 RETURNING *",[b,req.body.academic_year_id,req.body.exam_type_id,clean(req.body.grading_scale_id),req.body.exam_name,clean(req.body.class_id),clean(req.body.start_date),clean(req.body.end_date),clean(req.body.result_publish_date),req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'Exam not found.'});res.json({success:true,data:r.rows[0]})}catch(e){fail(res,e,'Failed to update exam.')}});
router.get("/exams/:id/subjects",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT es.*,UPPER(DATE_FORMAT(es.exam_date,'%d-%b-%Y')) AS exam_date,s.subject_code,s.subject_name FROM sms.exam_subjects es JOIN sms.subjects s ON s.subject_id=es.subject_id WHERE es.exam_id=$1 ORDER BY s.subject_name",[req.params.id]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load exam subjects.")}});
router.post("/exams/:id/subjects",requirePermission("exam.management","update"),async(req,res)=>{try{const b=req.body;if(!b.subject_id)return res.status(400).json({success:false,message:"Subject is required."});const exam=(await pool.query("SELECT e.*,br.institution_id FROM sms.exams e JOIN sms.branches br ON br.branch_id=e.branch_id WHERE e.exam_id=$1",[req.params.id])).rows[0];if(!exam)return res.status(404).json({success:false,message:"Exam not found."});if(exam.class_id){const assigned=await pool.query("SELECT 1 FROM sms.class_subjects WHERE institution_id=$1 AND class_id=$2 AND subject_id=$3 AND status='ACTIVE'",[exam.institution_id,exam.class_id,b.subject_id]);if(!assigned.rowCount)return res.status(400).json({success:false,message:"Assign this subject to the exam class first."});}const r=await pool.query("INSERT INTO sms.exam_subjects (exam_id,subject_id,full_marks,pass_marks,exam_date,start_time,end_time,room_no) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[req.params.id,b.subject_id,Number(b.full_marks||100),Number(b.pass_marks||33),clean(b.exam_date),clean(b.start_time),clean(b.end_time),clean(b.room_no)]);res.status(201).json({success:true,data:r.rows[0]})}catch(e){fail(res,e,"Failed to add exam subject.")}});
router.put("/exam-subjects/:id",requirePermission("exam.management","update"),async(req,res)=>{try{const b=req.body,r=await pool.query("UPDATE sms.exam_subjects SET full_marks=$1,pass_marks=$2,exam_date=$3,start_time=$4,end_time=$5,room_no=$6 WHERE exam_subject_id=$7 RETURNING *",[Number(b.full_marks),Number(b.pass_marks),clean(b.exam_date),clean(b.start_time),clean(b.end_time),clean(b.room_no),req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'Exam subject not found.'});res.json({success:true,data:r.rows[0]})}catch(e){fail(res,e,'Failed to update exam subject.')}});
router.delete("/exam-subjects/:id",requirePermission("exam.management","delete"),async(req,res)=>{try{const r=await pool.query("DELETE FROM sms.exam_subjects WHERE exam_subject_id=$1 RETURNING exam_subject_id",[req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'Exam subject not found.'});res.json({success:true})}catch(e){fail(res,e,'Failed to delete exam subject.')}});
router.post("/exams/:id/routine/generate",requirePermission("exam.management","update"),async(req,res)=>{try{const start=String(req.body.start_date||''),time=String(req.body.start_time||'10:00'),duration=Math.max(15,Number(req.body.duration_minutes||180)),skipFriday=req.body.skip_friday!==false;if(!/^\d{4}-\d{2}-\d{2}$/.test(start))return res.status(400).json({success:false,message:'A valid routine start date is required.'});const subjects=(await pool.query("SELECT exam_subject_id FROM sms.exam_subjects WHERE exam_id=$1 AND status='ACTIVE' ORDER BY exam_subject_id",[req.params.id])).rows;if(!subjects.length)return res.status(400).json({success:false,message:'Add exam subjects before generating a routine.'});let current=new Date(`${start}T00:00:00`);const [hour,minute]=time.split(':').map(Number);const endMinutes=hour*60+minute+duration,end=`${String(Math.floor(endMinutes/60)%24).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`;for(const subject of subjects){while(skipFriday&&current.getDay()===5)current.setDate(current.getDate()+1);const day=current.toISOString().slice(0,10);await pool.query("UPDATE sms.exam_subjects SET exam_date=$1,start_time=$2,end_time=$3 WHERE exam_subject_id=$4",[day,`${time}:00`,end,subject.exam_subject_id]);current.setDate(current.getDate()+1);}await pool.query("UPDATE sms.exams SET start_date=$1,end_date=$2,exam_status='SCHEDULED' WHERE exam_id=$3",[start,current.toISOString().slice(0,10),req.params.id]);res.json({success:true,data:{scheduled:subjects.length}})}catch(e){fail(res,e,'Failed to generate routine.')}});
router.post("/exams/:id/routine/reschedule",requirePermission("exam.management","update"),async(req,res)=>{try{const from=String(req.body.from_date||''),days=Number(req.body.shift_days||0);if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!Number.isInteger(days)||days===0)return res.status(400).json({success:false,message:'Select a date and a non-zero number of shift days.'});const r=await pool.query("UPDATE sms.exam_subjects SET exam_date=DATE_ADD(exam_date, INTERVAL $1 DAY) WHERE exam_id=$2 AND exam_date >= $3",[days,req.params.id,from]);const range=await pool.query("SELECT MIN(exam_date) start_date,MAX(exam_date) end_date FROM sms.exam_subjects WHERE exam_id=$1",[req.params.id]);await pool.query("UPDATE sms.exams SET start_date=$1,end_date=$2,exam_status='SCHEDULED' WHERE exam_id=$3",[range.rows[0]?.start_date,range.rows[0]?.end_date,req.params.id]);res.json({success:true,data:{rescheduled:r.rowCount}})}catch(e){fail(res,e,'Failed to reschedule routine.')}});
router.post("/exams/:id/candidates/generate",requirePermission("exam.management","update"),async(req,res)=>{try{const e=(await pool.query("SELECT * FROM sms.exams WHERE exam_id=$1",[req.params.id])).rows[0];if(!e)return res.status(404).json({success:false,message:"Exam not found."});const r=await pool.query("SELECT se.student_id,se.enrollment_id FROM sms.student_enrollments se WHERE se.branch_id=$1 AND se.academic_year_id=$2 AND (se.class_id=$3 OR $3 IS NULL) AND se.enrollment_status='ACTIVE'",[e.branch_id,e.academic_year_id,e.class_id]);let n=0;for(const row of r.rows){await pool.query("INSERT INTO sms.exam_candidates (exam_id,student_id,enrollment_id,candidate_no) VALUES ($1,$2,$3,$4) ON DUPLICATE KEY UPDATE enrollment_id=VALUES(enrollment_id)",[e.exam_id,row.student_id,row.enrollment_id,`${e.exam_id}-${String(++n).padStart(4,'0')}`]);}res.json({success:true,data:{generated:r.rows.length}})}catch(e){fail(res,e,"Failed to generate candidates.")}});
router.post("/exams/:id/seating/generate",requirePermission("exam.management","update"),async(req,res)=>{try{const exam=(await pool.query("SELECT branch_id FROM sms.exams WHERE exam_id=$1",[req.params.id])).rows[0];if(!exam)return res.status(404).json({success:false,message:'Exam not found.'});const rooms=(await pool.query("SELECT classroom_id,room_no,GREATEST(COALESCE(capacity,0),0) capacity FROM sms.classrooms WHERE branch_id=$1 AND status='ACTIVE' ORDER BY room_no",[exam.branch_id])).rows,candidates=(await pool.query("SELECT candidate_id FROM sms.exam_candidates WHERE exam_id=$1 AND eligibility_status='ELIGIBLE' ORDER BY candidate_no",[req.params.id])).rows;const capacity=rooms.reduce((sum,row)=>sum+Number(row.capacity),0);if(!candidates.length)return res.status(400).json({success:false,message:'Generate exam candidates first.'});if(capacity<candidates.length)return res.status(400).json({success:false,message:`Classroom capacity (${capacity}) is lower than candidates (${candidates.length}).`});await pool.query("DELETE FROM sms.exam_seating_assignments WHERE exam_id=$1",[req.params.id]);let i=0;for(const room of rooms)for(let seat=1;seat<=Number(room.capacity)&&i<candidates.length;seat++,i++)await pool.query("INSERT INTO sms.exam_seating_assignments (exam_id,candidate_id,classroom_id,seat_no) VALUES ($1,$2,$3,$4)",[req.params.id,candidates[i].candidate_id,room.classroom_id,`${room.room_no}-${seat}`]);res.json({success:true,data:{assigned:i}})}catch(e){fail(res,e,'Failed to generate seating plan.')}});
router.get("/exams/:id/seating",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT esa.*,ec.candidate_no,s.full_name,s.student_no,cr.room_no FROM sms.exam_seating_assignments esa JOIN sms.exam_candidates ec ON ec.candidate_id=esa.candidate_id JOIN sms.students s ON s.student_id=ec.student_id JOIN sms.classrooms cr ON cr.classroom_id=esa.classroom_id WHERE esa.exam_id=$1 ORDER BY cr.room_no,esa.seat_no",[req.params.id]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,'Failed to load seating plan.')}});
router.get("/exams/:id/candidates",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT ec.*,s.student_no,s.full_name FROM sms.exam_candidates ec JOIN sms.students s ON s.student_id=ec.student_id WHERE ec.exam_id=$1 ORDER BY ec.candidate_no",[req.params.id]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load candidates.")}});
router.get("/exams/:id/marks",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT es.exam_subject_id,s.subject_name,es.full_marks,es.pass_marks,ec.student_id,ec.candidate_no,st.full_name,em.mark_id,em.marks_obtained,em.is_absent,em.entry_status FROM sms.exam_subjects es JOIN sms.exam_candidates ec ON ec.exam_id=es.exam_id JOIN sms.students st ON st.student_id=ec.student_id JOIN sms.subjects s ON s.subject_id=es.subject_id LEFT JOIN sms.exam_marks em ON em.exam_subject_id=es.exam_subject_id AND em.student_id=ec.student_id WHERE es.exam_id=$1 ORDER BY s.subject_name,ec.candidate_no",[req.params.id]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load marks.")}});
router.put("/marks",requirePermission("exam.management","update"),async(req,res)=>{try{const rows=Array.isArray(req.body.marks)?req.body.marks:[];for(const m of rows){if(!m.exam_subject_id||!m.student_id)continue;const values=[Number(m.marks_obtained||0),m.is_absent?1:0,clean(m.remarks),m.entry_status==='VERIFIED'?'VERIFIED':'DRAFT',req.user.user_id,m.exam_subject_id,m.student_id];const updated=await pool.query("UPDATE sms.exam_marks SET marks_obtained=$1,is_absent=$2,remarks=$3,entry_status=$4,entered_by=$5 WHERE exam_subject_id=$6 AND student_id=$7 AND component_id IS NULL",values);if(!updated.rowCount){const subject=(await pool.query("SELECT exam_id FROM sms.exam_subjects WHERE exam_subject_id=$1",[m.exam_subject_id])).rows[0];if(!subject)throw new Error("Invalid exam subject.");await pool.query("INSERT INTO sms.exam_marks (exam_id,exam_subject_id,student_id,component_id,marks_obtained,is_absent,remarks,entry_status,entered_by) VALUES ($1,$2,$3,NULL,$4,$5,$6,$7,$8)",[subject.exam_id,m.exam_subject_id,m.student_id,values[0],values[1],values[2],values[3],values[4]]);}}res.json({success:true,data:{saved:rows.length}})}catch(e){fail(res,e,"Failed to save marks.")}});
router.post("/exams/:id/results/generate",requirePermission("exam.management","approve"),async(req,res)=>{const c=await pool.connect();try{await c.query("BEGIN");const subjects=(await c.query("SELECT * FROM sms.exam_subjects WHERE exam_id=$1",[req.params.id])).rows, candidates=(await c.query("SELECT * FROM sms.exam_candidates WHERE exam_id=$1 AND eligibility_status='ELIGIBLE'",[req.params.id])).rows;const exam=(await c.query("SELECT * FROM sms.exams WHERE exam_id=$1",[req.params.id])).rows[0];const grades=(await c.query("SELECT * FROM sms.grading_scale_details WHERE grading_scale_id=$1 ORDER BY min_marks DESC",[exam?.grading_scale_id])).rows;for(const x of candidates){let total=0,obtained=0,points=[],failed=0;const lines=[];for(const s of subjects){const m=(await c.query("SELECT * FROM sms.exam_marks WHERE exam_subject_id=$1 AND student_id=$2 AND component_id IS NULL",[s.exam_subject_id,x.student_id])).rows[0];const score=Number(m?.marks_obtained||0),abs=Boolean(m?.is_absent),percent=s.full_marks?score*100/Number(s.full_marks):0,g=grades.find(v=>percent>=Number(v.min_marks)&&percent<=Number(v.max_marks));const status=abs?'ABSENT':score>=Number(s.pass_marks)?'PASSED':'FAILED';if(status!=='PASSED')failed++;total+=Number(s.full_marks);obtained+=score;points.push(Number(g?.grade_point||0));lines.push({s,score,g,status});}const status=failed?'FAILED':'PASSED',gpa=status==='PASSED'&&points.length?points.reduce((a,b)=>a+b,0)/points.length:0;await c.query("INSERT INTO sms.student_results (exam_id,student_id,enrollment_id,total_marks,obtained_marks,gpa,letter_grade,result_status,failed_subject_count) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON DUPLICATE KEY UPDATE total_marks=VALUES(total_marks),obtained_marks=VALUES(obtained_marks),gpa=VALUES(gpa),letter_grade=VALUES(letter_grade),result_status=VALUES(result_status),failed_subject_count=VALUES(failed_subject_count)",[req.params.id,x.student_id,x.enrollment_id,total,obtained,gpa,status==='PASSED'?(grades.find(v=>Number(v.grade_point)===gpa)?.letter_grade||''):'F',status,failed]);const r=(await c.query("SELECT result_id FROM sms.student_results WHERE exam_id=$1 AND student_id=$2",[req.params.id,x.student_id])).rows[0];await c.query("DELETE FROM sms.student_result_details WHERE result_id=$1",[r.result_id]);for(const l of lines)await c.query("INSERT INTO sms.student_result_details (result_id,subject_id,full_marks,pass_marks,obtained_marks,letter_grade,grade_point,subject_status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[r.result_id,l.s.subject_id,l.s.full_marks,l.s.pass_marks,l.score,l.g?.letter_grade||'',l.g?.grade_point||0,l.status]);}await c.query("UPDATE sms.exams SET exam_status='COMPLETED' WHERE exam_id=$1",[req.params.id]);await c.query("COMMIT");res.json({success:true,data:{processed:candidates.length}})}catch(e){await c.query("ROLLBACK");fail(res,e,"Result generation failed.")}finally{c.release()}});
router.get("/exams/:id/results",requirePermission("exam.management","view"),async(req,res)=>{try{const r=await pool.query("SELECT sr.*,s.student_no,s.full_name FROM sms.student_results sr JOIN sms.students s ON s.student_id=sr.student_id WHERE sr.exam_id=$1 ORDER BY sr.gpa DESC,sr.obtained_marks DESC",[req.params.id]);res.json({success:true,data:r.rows})}catch(e){fail(res,e,"Failed to load results.")}});
router.post("/exams/:id/publish",requirePermission("exam.management","approve"),async(req,res)=>{try{await pool.query("UPDATE sms.exams SET exam_status='PUBLISHED' WHERE exam_id=$1",[req.params.id]);await pool.query("UPDATE sms.student_results SET published_at=NOW() WHERE exam_id=$1",[req.params.id]);res.json({success:true})}catch(e){fail(res,e,"Failed to publish result.")}});
router.post("/documents",requirePermission("exam.management","create"),async(req,res)=>{try{const type=String(req.body.document_type||'MARKSHEET').toUpperCase(),no=`${type.slice(0,3)}-${Date.now()}`,code=crypto.randomBytes(8).toString('hex').toUpperCase();const r=await pool.query("INSERT INTO sms.issued_documents (document_type,student_id,exam_id,document_no,issue_date,verification_code,issued_by) VALUES ($1,$2,$3,$4,CURDATE(),$5,$6) RETURNING *",[type,req.body.student_id,clean(req.body.exam_id),no,code,req.user.user_id]);res.status(201).json({success:true,data:r.rows[0]})}catch(e){fail(res,e,"Failed to issue document.")}});
export default router;
