<template>
  <section class="routine-page">
    <header class="hero"><div><small>EXAM OPERATIONS</small><h1>Routine & Seating</h1><p>Paper-aware exam schedule এবং classroom-based seating plan.</p></div><div class="actions"><button :disabled="!examId" @click="showGenerate = true">Generate routine</button><button class="secondary" :disabled="!examId" @click="showReschedule = true">Reschedule</button><button class="secondary" :disabled="!examId" @click="seating">Generate seating</button></div></header>
    <p v-if="msg" :class="['notice', kind]">{{ msg }}</p>
    <section class="selector"><label>Examination<select v-model="examId" @change="loadAll"><option value="">Select exam</option><option v-for="exam in exams" :key="exam.exam_id" :value="exam.exam_id">{{ exam.exam_name }} — {{ exam.class_name || 'All classes' }}</option></select></label><div><span>Scheduled subjects</span><b>{{ subjects.length }}</b></div><div><span>Assigned seats</span><b>{{ seats.length }}</b></div></section>
    <section class="panel"><div class="panel-head"><div><h2>Exam schedule</h2><p>একই subject-এর ১ম ও ২য় পত্র আলাদা row হিসেবে থাকবে।</p></div></div><div class="table-wrap"><table><thead><tr><th>Subject & paper</th><th>Date</th><th>Time</th><th>Room</th><th></th></tr></thead><tbody><tr v-for="row in subjects" :key="row.exam_subject_id"><td><b>{{ row.subject_name }}{{ paperLabel(row.paper_no) }}</b><small>{{ row.subject_code }}{{ paperLabelBn(row.paper_no) }}</small></td><td>{{ row.exam_date || '—' }}</td><td>{{ row.start_time || '—' }} – {{ row.end_time || '—' }}</td><td>{{ row.room_no || '—' }}</td><td class="right"><button class="mini" @click="edit(row)">Edit</button></td></tr><tr v-if="!subjects.length"><td colspan="5" class="empty">Select an exam or add exam subjects first.</td></tr></tbody></table></div></section>
    <section v-if="seats.length" class="panel"><div class="panel-head"><div><h2>Seating plan</h2><p>Room and seat allocation for eligible candidates.</p></div></div><div class="table-wrap"><table><thead><tr><th>Room</th><th>Seat</th><th>Candidate</th><th>Student</th></tr></thead><tbody><tr v-for="row in seats" :key="row.seating_assignment_id"><td>{{ row.room_no }}</td><td>{{ row.seat_no }}</td><td>{{ row.candidate_no }}</td><td><b>{{ row.full_name }}</b><small>{{ row.student_no }}</small></td></tr></tbody></table></div></section>

    <div v-if="showGenerate" class="backdrop"><form class="modal" @submit.prevent="generate"><div class="modal-head"><h2>Generate routine</h2><button type="button" @click="showGenerate = false">×</button></div><label>Start date<input v-model="generation.start_date" type="date" required /></label><label>Start time<input v-model="generation.start_time" type="time" required /></label><label>Duration (minutes)<input v-model.number="generation.duration_minutes" type="number" min="15" /></label><label class="check"><input v-model="generation.skip_friday" type="checkbox" /> শুক্রবার বাদ দিন</label><div class="modal-actions"><button type="button" class="secondary" @click="showGenerate = false">Cancel</button><button>Generate</button></div></form></div>
    <div v-if="showReschedule" class="backdrop"><form class="modal" @submit.prevent="reschedule"><div class="modal-head"><h2>Reschedule routine</h2><button type="button" @click="showReschedule = false">×</button></div><label>From date<input v-model="rescheduleForm.from_date" type="date" required /></label><label>Shift days<input v-model.number="rescheduleForm.shift_days" type="number" required placeholder="+2 / -1" /></label><div class="modal-actions"><button type="button" class="secondary" @click="showReschedule = false">Cancel</button><button>Save</button></div></form></div>
    <div v-if="editRow" class="backdrop"><form class="modal" @submit.prevent="saveEdit"><div class="modal-head"><div><h2>{{ editRow.subject_name }}{{ paperLabel(editRow.paper_no) }}</h2><small>{{ editRow.subject_code }}</small></div><button type="button" @click="editRow = null">×</button></div><label>Exam date<input v-model="editForm.exam_date" type="date" /></label><label>Start time<input v-model="editForm.start_time" type="time" /></label><label>End time<input v-model="editForm.end_time" type="time" /></label><label>Room<input v-model="editForm.room_no" placeholder="Classroom / Room No" /></label><div class="modal-actions"><button type="button" class="secondary" @click="editRow = null">Cancel</button><button>Update</button></div></form></div>
  </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';
import api from '../../services/api';

const today = () => { const date = new Date(); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 10); };
const exams = ref([]), subjects = ref([]), seats = ref([]), examId = ref(''), showGenerate = ref(false), showReschedule = ref(false), editRow = ref(null), msg = ref(''), kind = ref('success');
const generation = reactive({ start_date: today(), start_time: '10:00', duration_minutes: 180, skip_friday: true });
const rescheduleForm = reactive({ from_date: '', shift_days: 1 });
const editForm = reactive({ exam_date: '', start_time: '', end_time: '', room_no: '' });
const paperLabel = (value) => Number(value) === 1 ? ' — 1st Paper' : Number(value) === 2 ? ' — 2nd Paper' : '';
const paperLabelBn = (value) => Number(value) === 1 ? ' · ১ম পত্র' : Number(value) === 2 ? ' · ২য় পত্র' : '';
const note = (text, type = 'success') => { msg.value = text; kind.value = type; };
async function loadAll() { if (!examId.value) { subjects.value = []; seats.value = []; return; } try { const [subjectResponse, seatResponse] = await Promise.all([api.get(`/exams/exams/${examId.value}/subjects`), api.get(`/exams/exams/${examId.value}/seating`)]); subjects.value = subjectResponse.data.data || []; seats.value = seatResponse.data.data || []; } catch (error) { note(error.response?.data?.message || 'Could not load routine.', 'error'); } }
async function generate() { try { await api.post(`/exams/exams/${examId.value}/routine/generate`, generation); showGenerate.value = false; note('Routine generated.'); await loadAll(); } catch (error) { note(error.response?.data?.message || 'Routine generation failed.', 'error'); } }
async function reschedule() { try { await api.post(`/exams/exams/${examId.value}/routine/reschedule`, rescheduleForm); showReschedule.value = false; note('Routine rescheduled.'); await loadAll(); } catch (error) { note(error.response?.data?.message || 'Reschedule failed.', 'error'); } }
function edit(row) { editRow.value = row; Object.assign(editForm, { exam_date: String(row.exam_date || '').slice(0, 10), start_time: String(row.start_time || '').slice(0, 5), end_time: String(row.end_time || '').slice(0, 5), room_no: row.room_no || '' }); }
async function saveEdit() { try { await api.put(`/exams/exam-subjects/${editRow.value.exam_subject_id}`, { ...editRow.value, ...editForm }); editRow.value = null; note('Schedule updated.'); await loadAll(); } catch (error) { note(error.response?.data?.message || 'Update failed.', 'error'); } }
async function seating() { try { const response = await api.post(`/exams/exams/${examId.value}/seating/generate`); note(`${response.data.data.assigned} candidates seated.`); await loadAll(); } catch (error) { note(error.response?.data?.message || 'Seating generation failed.', 'error'); } }
onMounted(async () => { try { exams.value = (await api.get('/exams/exams')).data.data || []; } catch (error) { note(error.response?.data?.message || 'Could not load examinations.', 'error'); } });
</script>

<style scoped>
.routine-page{display:grid;gap:16px;color:#172033}.hero,.selector,.panel{border:1px solid #e2e8f0;border-radius:16px;background:#fff}.hero{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:21px 22px;background:linear-gradient(125deg,#f8faff,#eef2ff)}.hero small{color:#4f46e5;font-size:9px;font-weight:900;letter-spacing:.13em}.hero h1{margin:4px 0;font-size:25px}.hero p,.panel-head p{margin:0;color:#64748b;font-size:12px}.actions,.modal-actions{display:flex;gap:8px}button{height:39px;padding:0 12px;border:0;border-radius:8px;background:#4338ca;color:#fff;font:inherit;font-size:11px;font-weight:850;cursor:pointer}button.secondary{border:1px solid #cbd5e1;background:#fff;color:#475569}button:disabled{cursor:not-allowed;opacity:.45}.notice{margin:0;padding:10px 12px;border-radius:9px;font-size:12px;font-weight:750}.notice.success{background:#ecfdf5;color:#047857}.notice.error{background:#fff1f2;color:#be123c}.selector{display:grid;grid-template-columns:minmax(260px,1fr) 160px 160px;gap:12px;align-items:end;padding:14px}.selector label,.modal label{display:grid;gap:5px;color:#334155;font-size:10px;font-weight:850}.selector select,.modal input{width:100%;height:43px;padding:0 11px;border:1px solid #d7e0ec;border-radius:9px;background:#fff;font:inherit;box-sizing:border-box}.selector>div{padding:8px 11px;border-radius:9px;background:#f8fafc}.selector span,.selector b{display:block}.selector span{color:#64748b;font-size:9px}.selector b{margin-top:4px;font-size:18px}.panel{overflow:hidden}.panel-head{padding:16px 17px;border-bottom:1px solid #edf1f6}.panel-head h2{margin:0 0 3px;font-size:16px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:11px 13px;border-bottom:1px solid #edf1f6;text-align:left;font-size:12px}th{background:#f8fafc;color:#64748b;font-size:9px;text-transform:uppercase}td b,td small{display:block}td small{margin-top:3px;color:#64748b}.right{text-align:right}.mini{height:30px;padding:0 9px}.empty{padding:35px!important;text-align:center;color:#94a3b8}.backdrop{position:fixed;inset:0;z-index:1100;display:grid;place-items:center;padding:16px;background:#0f172aa8}.modal{display:grid;gap:11px;width:min(430px,100%);padding:20px;border-radius:15px;background:#fff}.modal-head{display:flex;align-items:start;justify-content:space-between}.modal-head h2{margin:0;font-size:17px}.modal-head button{width:32px;height:32px;padding:0;background:#f1f5f9;color:#475569;font-size:18px}.check{display:flex!important;align-items:center;grid-template-columns:auto 1fr}.check input{width:17px;height:17px}.modal-actions{justify-content:flex-end;margin-top:4px}@media(max-width:760px){.hero,.actions{align-items:stretch;flex-direction:column}.selector{grid-template-columns:1fr 1fr}.selector label{grid-column:1/-1}}
</style>
